### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by amkrajewski** [mcgalcode/pylattica#13]
Here is a list of comments regarding the software for my review of your JOSS submission. I will open a separate issue for the manuscript to keep things organized.

- **The review was a pleasure to complete. _pylattica_ is well written, and its codebase is clearly organized into a directory structure**, which is relatively easy to navigate thanks to the good naming of things.

- Installation instructions are missing and should be added for novice Python users, but a simple `pip install -e .` everything went smoothly for me on a clean VM I've set up to play with it. All tests passed in just under 20s.

- The documentation contains several neat, runnable examples (guides) that appear to be Jupyter notebooks. Placing them in a dedicated directory in the repository would be great. I couldn't find them currently.

- It's great to see that functions (almost) always have type hints correctly following PEP 484, significantly improving end-user experience and reducing the possibility of incorrect use, especially considering numerous custom classes.

- The coverage is tested with Codecov, and it's 98, which is excellent. A minor issue is that the badge in the README does not link to the actual report.

- Tests are run on the Ubuntu Linux with Python 3.8-10. Authors may want to bump that to 3.9-11, as Python 3.8 is about to reach end-of-life in a couple of months, while Python 3.11 is the oldest version actively receiving non-security bug fixes. Adding Windows and Mac to the test matrix would also be nice.

- Docstrings are occasionally missing in important places: https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/structures/square_grid/growth_setup.py#L7 or have been created as templates with no information
https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/structures/square_grid/grid_setup.py#L177-L181

- In some regions of the codebase, Python classes seem to be defined just to provide different inputs such as simple string values https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/models/game_of_life/controller.py#L51-L52
to the procedure running the simulation. I can see the usefulness in more complex cases, but it may be undesirable here as it obscures usage from the end customers and crowds the package namespace.

- Relative https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/models/growth/growth_controller.py#L1 and absolute https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/models/game_of_life/controller.py#L1 imports are not used consistently decreasing readability.

- [Google](https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/structures/square_grid/grid_setup.py#L26) and [NumPy](https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/discrete/discrete_state_result_analyzer.py#L30) docstring styles are mixed / not used consistently. It may be the reason [parts of the documentation](https://mcgalcode.github.io/pylattica/reference/core/lattice/) are not processed correctly.

- In [parts of the documentation](https://mcgalcode.github.io/pylattica/guides/neighborhoods/), some images do not display correctly (for me), and some links, e.g., to the CHANGELOG, are broken.

**Comment by mcgalcode** [comment]
Hello again @amkrajewski! Another checklist for my own reference:

- [x] Installation instructions
- [x] Add instructions for running tests
- [x] Either move or clarify location of example notebooks
- [x] Readme codecov badge link fix
- [x] At the very least, bump python version in testing matrix, try adding windows + mac as well
- [x] Add doc strings in places where they are missing
- [x] Identify classes that could be enums and refactor
- [x] Unify imports to relative format
- [x] Unify docstring styles
- [x] Fix broken images and links in documentation

**Comment by mcgalcode** [comment]
Hi @amkrajewski, I've done my best to address your comments here! Let me know what you think (reflected in the master branch, and the paper branch).

**Comment by amkrajewski** [comment]
Hi @mcgalcode! The changes you've made look great! I think it's pretty much ready! Let me have a bit closer look tomorrow, but all of my original concerns are addressed.

I caught a couple minor things looking through, but fixing them shouldn't take more than a few minutes:
- For the development install instructions in README, you may want to add `-e`, so that it installs in editable mode and changes when users play with it.
- You may want to consider removing CHANGELOG file (empty now) and writing release notes through GitHub. It's way more pleasant to maintain and notifies people when you release. Also, the changelog on PyPI (set in `pyproject.toml`) is pointing to not existing doc page.
- The `setuptools` version required by build system should likely be 61 or higher based on project structure.
- The date in license is old I think.
- The license on PyPI (set in `pyproject.toml`) is not MIT.

**Comment by mcgalcode** [comment]
Hi @amkrajewski ! Ah thanks, these are some good catches. I fixed them all (and agree re: removing CHANGELOG), except for the first - I've got `pip install -e . ` under the **Development** section.

**Comment by amkrajewski** [comment]
All looks good!

**Comment by mcgalcode** [comment]
Thanks for all these helpful comments @amkrajewski!
