### ISSUE TITLE
Game of Life controller (example notebook) is not performing correctly

### ISSUE THREAD

**Issue by mattmcdermott** [mcgalcode/pylattica#2]
The Game of Life example Jupyter notebook (`docs/examples/game_of_life.ipynb`) does not currently perform as intended. At the moment, all cells in the simulation die after just 15-20 steps.

See GIF below:

![test](https://user-images.githubusercontent.com/40469694/201189562-2ce93f61-553e-4532-b88f-fef9278b2c1d.gif)

**Comment by mcgalcode** [comment]
Fixed!
