### ISSUE TITLE
Plotting with `DiscreteSquareGridResultArtist` changes color scheme and has noise

### ISSUE THREAD

**Issue by mattmcdermott** [mcgalcode/pylattica#3]
In the GIF posted in #2, when all cells die (i.e., 2 phases --> 1 phase), the plotter `DiscreteSquareGridResultArtist` changes its color scheme. It also introduces noise in the plot.

It would be expected behavior by the user to maintain a color scheme across all steps, regardless of which phases are currently present in the simulation step.

**Comment by mcgalcode** [comment]
Fixed!
